name: flutter_e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  iconsax: ^0.0.8
  intl: ^0.20.2
  logger: ^2.3.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^4.2.0
  lottie: ^3.1.2
  connectivity_plus: ^6.0.5
  cloud_firestore: ^6.0.0
  google_sign_in: ^7.1.1
  image_picker: ^1.1.2
  firebase_storage: ^13.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_sslcommerz: ^2.3.9
  flutter_dotenv: ^5.2.1
  firebase_auth: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/images/onboarding_images/
    - assets/images/other_images/
    - .env
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.otf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.otf
          style: italic
        - asset: assets/fonts/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.otf
          weight: 800
      
